### ISSUE TITLE
Switch to using Assets for Buildings/Units/Research/Abilities

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#129]
Switch to using Assets for Buildings/Units/Research/Abilities 🙂

**Comment by kurozael** [comment]
This particular one is unlikely to happen because assets do not offer the kind of flexibility needed for different logic and dependencies. It would be much more jarring trying to work these into the asset system just for the sake of it, especially since some of these have custom entity types and the asset inspector is very limited.
